"""
Paytriage - AI Payment Recovery Agent
=====================================

Reads a batch of failed recurring payments, decides a recovery strategy for
each one, runs a bounded recovery sequence, and reports how much revenue was
recovered.

IMPORTANT - WHAT IS REAL AND WHAT IS SIMULATED
----------------------------------------------
Real:      the decision policy, the escalation ladder, the stopping rules,
           and the audit trail. These are the product.
Simulated: whether an individual retry attempt succeeds. There is no live
           payment gateway here, so outcomes are drawn from per-reason
           success rates defined in RECOVERY_ODDS below. Those rates are
           stated assumptions, not measurements.

The simulation is seeded (--seed, default 42) so every run on the same input
produces identical output. Reproducibility is the point: the numbers in the
README came from `python agent.py` and can be regenerated by anyone.

Usage:
    python agent.py
    python agent.py --input data/sample_payments.json --output results/recovery_results.json
    python agent.py --seed 7

Requires Python 3.9+. Standard library only.
"""

from __future__ import annotations

import argparse
import json
import random
import sys
from collections import defaultdict
from dataclasses import dataclass, field, asdict
from datetime import date
from pathlib import Path
from typing import Any


# ---------------------------------------------------------------------------
# Policy constants
#
# Every number below is a tunable assumption. They are gathered here rather
# than scattered through the code so that a reviewer can see the whole policy
# in one screen and argue with it.
# ---------------------------------------------------------------------------

# Hard ceiling on retry attempts per payment. This is the anti-spam guarantee:
# no customer is contacted or charged more than this many times, ever.
MAX_ATTEMPTS = 3

# A customer must have at least this many prior successful payments before we
# will spend a recovery attempt on them. Brand-new customers are a retention
# problem, not a recovery problem.
MIN_HISTORY_FOR_RECOVERY = 3

# Below this lifetime value, recovery effort costs more than it returns.
MIN_CLV_FOR_RECOVERY = 1500

# Bank declines from thin-history customers are the classic fraud signature.
# We refuse to retry them at all, regardless of amount.
BANK_DECLINE_MIN_HISTORY = 5

# Probability that a single attempt succeeds, by failure reason.
# Rationale for each is in architecture.md.
RECOVERY_ODDS = {
    "card_expired": 0.72,       # customer updates card when prompted
    "insufficient_funds": 0.45,  # depends on payday timing
    "network_error": 0.85,       # usually transient, resolves on its own
    "bank_decline": 0.18,        # often a persistent block, not a glitch
}

# Segment multipliers applied to the base odds above. A loyal customer is more
# likely to act on a recovery prompt than a lapsing one.
SEGMENT_MULTIPLIER = {
    "loyal": 1.15,
    "at_risk": 0.75,
    "new": 0.55,
}

# Unknown failure reasons fall back to this. Conservative on purpose.
UNKNOWN_REASON_ODDS = 0.20

# Strategy definitions: how many attempts the ladder allows, and how many days
# to wait before each attempt. len(delays) is the attempt budget.
STRATEGIES = {
    # Transient or trivially-fixable failures. Hit it now, once more tomorrow.
    "immediate_retry": {"delays_days": [0, 1, 3]},
    # Customer has to do something (top up, update card). Tell them, then wait.
    "notify_then_retry": {"delays_days": [0, 2, 5]},
    # Something is wrong that a retry cannot fix. A human opens a ticket.
    "customer_contact": {"delays_days": [1]},
    # Not worth pursuing. Zero attempts, zero customer contact.
    "skip": {"delays_days": []},
}


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------

REQUIRED_FIELDS = ("payment_id", "amount", "failure_reason")


@dataclass
class Payment:
    """One failed payment, normalised from the input JSON."""

    payment_id: str
    amount: int
    failure_reason: str
    merchant_id: str = "unknown"
    customer_id: str = "unknown"
    currency: str = "INR"
    customer_history: str = "new"
    subscription_type: str = "monthly"
    previous_successful_payments: int = 0
    days_since_last_payment: int = 0
    customer_lifetime_value: int = 0

    @classmethod
    def from_dict(cls, raw: dict[str, Any]) -> "Payment":
        """Build a Payment, raising ValueError on anything unusable."""
        missing = [f for f in REQUIRED_FIELDS if raw.get(f) in (None, "")]
        if missing:
            raise ValueError(f"missing required field(s): {', '.join(missing)}")

        try:
            amount = int(raw["amount"])
        except (TypeError, ValueError) as exc:
            raise ValueError(f"amount is not a number: {raw.get('amount')!r}") from exc

        if amount <= 0:
            raise ValueError(f"amount must be positive, got {amount}")

        # Only keep keys the dataclass knows about; ignore extras silently so
        # that a richer upstream schema does not break us.
        known = {f for f in cls.__dataclass_fields__}
        clean = {k: v for k, v in raw.items() if k in known}
        clean["amount"] = amount

        # Coerce the numeric fields we tolerate being absent or stringly-typed.
        for field_name in (
            "previous_successful_payments",
            "days_since_last_payment",
            "customer_lifetime_value",
        ):
            try:
                clean[field_name] = int(clean.get(field_name, 0) or 0)
            except (TypeError, ValueError):
                clean[field_name] = 0

        return cls(**clean)


@dataclass
class Decision:
    """The policy engine's verdict on a single payment."""

    should_recover: bool
    strategy: str
    reasoning: str
    confidence: str  # high | medium | low


@dataclass
class Attempt:
    """One entry in the escalation ladder."""

    attempt_number: int
    day_offset: int
    action: str
    outcome: str  # success | failed


@dataclass
class CaseResult:
    """Everything that happened to one payment. This is the audit record."""

    payment_id: str
    customer_id: str
    amount: int
    failure_reason: str
    customer_history: str
    previous_successful_payments: int
    customer_lifetime_value: int
    decision: str            # recover | skip
    strategy: str
    reasoning: str
    confidence: str
    attempts: list[Attempt] = field(default_factory=list)
    outcome: str = "not_attempted"  # recovered | unrecovered | not_attempted
    recovered_amount: int = 0
    stopped_because: str = ""


# ---------------------------------------------------------------------------
# Policy engine - the decisions
# ---------------------------------------------------------------------------

class PolicyEngine:
    """Decides whether and how to pursue a failed payment.

    Deterministic and explainable by design: every branch writes the reason it
    fired into the audit trail, so any decision can be traced back to a rule
    rather than to a model's mood.
    """

    def decide(self, p: Payment) -> Decision:
        history = p.previous_successful_payments
        clv = p.customer_lifetime_value
        reason = p.failure_reason
        segment = p.customer_history

        # ---- Refusal rules. Checked first; these are the guardrails. ----

        if reason == "bank_decline" and history < BANK_DECLINE_MIN_HISTORY:
            return Decision(
                False,
                "skip",
                f"Bank decline with only {history} prior payments. Thin history plus "
                f"an issuer block is the common fraud signature; retrying risks "
                f"chargebacks and issuer penalties. Refer to onboarding review instead.",
                "high",
            )

        if history < MIN_HISTORY_FOR_RECOVERY:
            return Decision(
                False,
                "skip",
                f"Only {history} prior successful payment(s), below the threshold of "
                f"{MIN_HISTORY_FOR_RECOVERY}. Too little signal that this customer "
                f"intends to keep paying. This is a retention problem, not a recovery one.",
                "high",
            )

        if clv < MIN_CLV_FOR_RECOVERY:
            return Decision(
                False,
                "skip",
                f"Lifetime value of {clv} is below the {MIN_CLV_FOR_RECOVERY} floor. "
                f"Expected recovery does not cover the cost of contacting the customer.",
                "high",
            )

        # ---- Routing rules. The customer is worth pursuing; pick the ladder. ----

        if reason == "bank_decline":
            return Decision(
                True,
                "customer_contact",
                f"Bank decline from an established customer ({history} prior payments). "
                f"A retry cannot clear an issuer block, so this needs a human to find out "
                f"whether it is a fraud hold, a lapsed mandate, or a closed account.",
                "low",
            )

        if reason == "network_error":
            return Decision(
                True,
                "immediate_retry",
                f"Network error is a gateway-side fault, not a customer-side one. "
                f"Nothing for the customer to fix and no reason to notify them. "
                f"Retry immediately.",
                "high",
            )

        if reason == "card_expired":
            # The customer must physically update a card, so notification comes
            # first. The exception is a long-tenured customer, where an immediate
            # retry often clears on the network's updated-card service before we
            # ever need to bother them.
            if history >= 15:
                return Decision(
                    True,
                    "immediate_retry",
                    f"Card expired for a long-tenured customer ({history} payments). "
                    f"Try the account updater path first; if it clears, the customer "
                    f"never has to be contacted at all.",
                    "high",
                )
            return Decision(
                True,
                "notify_then_retry",
                f"Card expired and the customer has to enter new details. Notify first, "
                f"then retry. Retrying without telling them just burns attempts.",
                "medium",
            )

        if reason == "insufficient_funds":
            confidence = "high" if segment == "loyal" else "low"
            return Decision(
                True,
                "notify_then_retry",
                f"Insufficient funds from a {segment} customer. Likely a timing problem "
                f"rather than an intent problem, so notify and space the retries across "
                f"a pay cycle instead of hammering the same empty account.",
                confidence,
            )

        # ---- Unknown reason. Do the cautious thing, and say so. ----
        return Decision(
            True,
            "customer_contact",
            f"Unrecognised failure reason '{reason}'. Routed to human review rather than "
            f"guessing at an automated remedy.",
            "low",
        )


# ---------------------------------------------------------------------------
# Recovery simulator - the outcomes
# ---------------------------------------------------------------------------

class RecoverySimulator:
    """Runs the escalation ladder for a decided payment.

    Every attempt outcome here is a coin flip weighted by RECOVERY_ODDS. It is
    a model of a payment gateway, not a payment gateway. Swapping this class for
    real Razorpay test-mode calls is the intended next step and would not
    require touching PolicyEngine.
    """

    def __init__(self, rng: random.Random):
        self.rng = rng

    def _odds(self, p: Payment, attempt_number: int) -> float:
        base = RECOVERY_ODDS.get(p.failure_reason, UNKNOWN_REASON_ODDS)
        base *= SEGMENT_MULTIPLIER.get(p.customer_history, 0.6)

        # Each successive attempt on the same payment is less likely to work
        # than the one before. If the first two failed, the third rarely saves it.
        base *= 0.65 ** (attempt_number - 1)

        return max(0.0, min(base, 0.95))

    def run(self, p: Payment, decision: Decision) -> CaseResult:
        result = CaseResult(
            payment_id=p.payment_id,
            customer_id=p.customer_id,
            amount=p.amount,
            failure_reason=p.failure_reason,
            customer_history=p.customer_history,
            previous_successful_payments=p.previous_successful_payments,
            customer_lifetime_value=p.customer_lifetime_value,
            decision="recover" if decision.should_recover else "skip",
            strategy=decision.strategy,
            reasoning=decision.reasoning,
            confidence=decision.confidence,
        )

        if not decision.should_recover:
            result.outcome = "not_attempted"
            result.stopped_because = "policy_declined_recovery"
            return result

        delays = STRATEGIES[decision.strategy]["delays_days"]
        # The global ceiling wins even if a strategy asks for more.
        delays = delays[:MAX_ATTEMPTS]

        for i, day_offset in enumerate(delays, start=1):
            if decision.strategy == "customer_contact":
                action = "support ticket raised for manual investigation"
            elif decision.strategy == "notify_then_retry" and i == 1:
                action = "notification sent, then charge retried"
            else:
                action = "charge retried"

            succeeded = self.rng.random() < self._odds(p, i)
            result.attempts.append(
                Attempt(
                    attempt_number=i,
                    day_offset=day_offset,
                    action=action,
                    outcome="success" if succeeded else "failed",
                )
            )

            if succeeded:
                result.outcome = "recovered"
                result.recovered_amount = p.amount
                result.stopped_because = "recovered_on_attempt_%d" % i
                return result

        result.outcome = "unrecovered"
        result.stopped_because = (
            f"exhausted_attempt_budget_after_{len(delays)}"
            if delays
            else "no_attempts_configured"
        )
        return result


# ---------------------------------------------------------------------------
# Aggregation
# ---------------------------------------------------------------------------

def _pct(numerator: float, denominator: float) -> float:
    """Percentage, rounded to one place, safe when the denominator is zero."""
    if not denominator:
        return 0.0
    return round(100.0 * numerator / denominator, 1)


def _empty_bucket() -> dict[str, int]:
    return {"count": 0, "amount": 0, "attempted": 0, "recovered": 0, "recovered_amount": 0}


def build_report(
    results: list[CaseResult],
    skipped_records: list[dict[str, str]],
    seed: int,
) -> dict[str, Any]:
    total_amount = sum(r.amount for r in results)
    attempted = [r for r in results if r.decision == "recover"]
    recovered = [r for r in results if r.outcome == "recovered"]
    recovered_amount = sum(r.recovered_amount for r in results)

    by_reason: dict[str, dict[str, int]] = defaultdict(_empty_bucket)
    by_segment: dict[str, dict[str, int]] = defaultdict(_empty_bucket)
    by_strategy: dict[str, dict[str, int]] = defaultdict(_empty_bucket)

    for r in results:
        for bucket in (
            by_reason[r.failure_reason],
            by_segment[r.customer_history],
            by_strategy[r.strategy],
        ):
            bucket["count"] += 1
            bucket["amount"] += r.amount
            if r.decision == "recover":
                bucket["attempted"] += 1
            if r.outcome == "recovered":
                bucket["recovered"] += 1
                bucket["recovered_amount"] += r.recovered_amount

    def finish(buckets: dict[str, dict[str, int]]) -> dict[str, dict[str, Any]]:
        out = {}
        for key, b in sorted(buckets.items()):
            out[key] = {
                **b,
                "recovery_rate_percent": _pct(b["recovered"], b["count"]),
                "attempt_success_rate_percent": _pct(b["recovered"], b["attempted"]),
            }
        return out

    total_attempts = sum(len(r.attempts) for r in results)

    return {
        "metadata": {
            "project": "Paytriage",
            "track": "AI Revenue Recovery",
            "generated_on": date.today().isoformat(),
            "generated_by": "agent.py",
            "random_seed": seed,
            "outcomes_are_simulated": True,
            "simulation_note": (
                "Decision policy, escalation ladder, stopping rules and audit trail are "
                "real. Individual attempt outcomes are drawn from the assumed per-reason "
                "success rates in RECOVERY_ODDS, not from a live payment gateway."
            ),
            "policy": {
                "max_attempts_per_payment": MAX_ATTEMPTS,
                "min_prior_payments_for_recovery": MIN_HISTORY_FOR_RECOVERY,
                "min_customer_lifetime_value": MIN_CLV_FOR_RECOVERY,
                "bank_decline_min_history": BANK_DECLINE_MIN_HISTORY,
                "assumed_base_odds": RECOVERY_ODDS,
                "segment_multipliers": SEGMENT_MULTIPLIER,
            },
        },
        "summary": {
            "payments_processed": len(results),
            "malformed_records_skipped": len(skipped_records),
            "amount_at_risk": total_amount,
            "recovery_attempted": len(attempted),
            "recovery_declined": len(results) - len(attempted),
            "recovered_count": len(recovered),
            "recovered_amount": recovered_amount,
            "unrecovered_amount": total_amount - recovered_amount,
            "recovery_rate_percent": _pct(len(recovered), len(results)),
            "attempt_success_rate_percent": _pct(len(recovered), len(attempted)),
            "amount_recovery_rate_percent": _pct(recovered_amount, total_amount),
            "total_customer_touches": total_attempts,
            "avg_touches_per_pursued_payment": (
                round(total_attempts / len(attempted), 2) if attempted else 0.0
            ),
        },
        "by_failure_reason": finish(by_reason),
        "by_customer_segment": finish(by_segment),
        "by_strategy": finish(by_strategy),
        "malformed_records": skipped_records,
        "audit_log": [asdict(r) for r in results],
    }


# ---------------------------------------------------------------------------
# I/O
# ---------------------------------------------------------------------------

def load_payments(path: Path) -> tuple[list[Payment], list[dict[str, str]]]:
    """Load and validate payments. Returns (usable, rejected-with-reasons)."""
    try:
        raw_text = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        raise SystemExit(
            f"Input file not found: {path}\n"
            f"Expected the payments file there. Pass a different path with --input."
        )
    except OSError as exc:
        raise SystemExit(f"Could not read {path}: {exc}")

    try:
        data = json.loads(raw_text)
    except json.JSONDecodeError as exc:
        raise SystemExit(f"{path} is not valid JSON: {exc}")

    # Accept either {"failed_payments": [...]} or a bare [...].
    if isinstance(data, dict):
        records = data.get("failed_payments")
        if records is None:
            raise SystemExit(
                f"{path} is a JSON object but has no 'failed_payments' key. "
                f"Found keys: {', '.join(sorted(data)) or '(none)'}"
            )
    elif isinstance(data, list):
        records = data
    else:
        raise SystemExit(f"{path} must contain a list or an object, got {type(data).__name__}")

    if not isinstance(records, list):
        raise SystemExit("'failed_payments' must be a list.")

    payments: list[Payment] = []
    rejected: list[dict[str, str]] = []
    seen_ids: set[str] = set()

    for index, record in enumerate(records):
        if not isinstance(record, dict):
            rejected.append({"index": str(index), "error": "record is not an object"})
            continue
        try:
            payment = Payment.from_dict(record)
        except ValueError as exc:
            rejected.append(
                {
                    "index": str(index),
                    "payment_id": str(record.get("payment_id", "<none>")),
                    "error": str(exc),
                }
            )
            continue

        if payment.payment_id in seen_ids:
            rejected.append(
                {
                    "index": str(index),
                    "payment_id": payment.payment_id,
                    "error": "duplicate payment_id; first occurrence kept",
                }
            )
            continue

        seen_ids.add(payment.payment_id)
        payments.append(payment)

    return payments, rejected


def write_report(report: dict[str, Any], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")


def print_summary(report: dict[str, Any]) -> None:
    s = report["summary"]
    line = "-" * 62

    print()
    print("PAYTRIAGE - RECOVERY RUN")
    print(line)
    print(f"  Payments processed        {s['payments_processed']}")
    if s["malformed_records_skipped"]:
        print(f"  Malformed records skipped {s['malformed_records_skipped']}")
    print(f"  Amount at risk            INR {s['amount_at_risk']:,}")
    print()
    print(f"  Pursued                   {s['recovery_attempted']}")
    print(f"  Declined by policy        {s['recovery_declined']}")
    print(f"  Recovered                 {s['recovered_count']}")
    print()
    print(f"  Amount recovered          INR {s['recovered_amount']:,}")
    print(f"  Amount written off        INR {s['unrecovered_amount']:,}")
    print(f"  Amount recovery rate      {s['amount_recovery_rate_percent']}%")
    print(f"  Success rate when pursued {s['attempt_success_rate_percent']}%")
    print()
    print(f"  Customer touches          {s['total_customer_touches']}")
    print(f"  Avg touches when pursued  {s['avg_touches_per_pursued_payment']}")
    print(line)

    print("\nBy failure reason")
    for reason, b in report["by_failure_reason"].items():
        print(
            f"  {reason:<20} {b['recovered']:>2}/{b['count']:<3} "
            f"INR {b['recovered_amount']:>7,} recovered  "
            f"({b['recovery_rate_percent']}%)"
        )

    print("\nBy customer segment")
    for segment, b in report["by_customer_segment"].items():
        print(
            f"  {segment:<20} {b['recovered']:>2}/{b['count']:<3} "
            f"INR {b['recovered_amount']:>7,} recovered  "
            f"({b['recovery_rate_percent']}%)"
        )
    print()


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Paytriage - triage and recover failed recurring payments.",
    )
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("data/sample_payments.json"),
        help="Path to the failed-payments JSON file.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("results/recovery_results.json"),
        help="Where to write the recovery report.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Seed for the outcome simulator. Same seed, same results.",
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="Write the report without printing the summary.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)

    payments, rejected = load_payments(args.input)

    if not payments:
        print(f"No usable payments found in {args.input}.", file=sys.stderr)
        if rejected:
            print(f"{len(rejected)} record(s) were rejected:", file=sys.stderr)
            for r in rejected[:5]:
                print(f"  - {r}", file=sys.stderr)
        return 1

    if rejected:
        print(
            f"Warning: skipped {len(rejected)} malformed record(s). "
            f"Details are in the report under 'malformed_records'.",
            file=sys.stderr,
        )

    engine = PolicyEngine()
    simulator = RecoverySimulator(random.Random(args.seed))

    results = [simulator.run(p, engine.decide(p)) for p in payments]

    report = build_report(results, rejected, args.seed)
    write_report(report, args.output)

    if not args.quiet:
        print_summary(report)
        print(f"Full audit trail written to {args.output}\n")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
